<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ros2_fra2mo)/urdf/utility_macro.xacro" />

  <xacro:macro name="fra2mo_base" params="prefix">

    <xacro:property name="base_height" value="0.180" /> 
    <xacro:property name="base_radius" value="0.11" /> 
    <xacro:property name="base_mass" value="5" />
    <xacro:property name="wheel_mass" value="2.5" />
    <xacro:property name="wheel_radius" value="0.035" /> 
    <xacro:property name="wheel_axle" value="0.124" /> 

    <link name="${prefix}base_footprint"/>

    <link name="${prefix}base_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${base_mass}" />
        <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
      </inertial>
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_body.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Blue" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <geometry> <cylinder length="${base_height}" radius="${base_radius}" /> </geometry>
        <origin xyz="0 0.0 ${(base_height/2.0)-0.05}" rpy="0 0 0" />
      </collision> 
      <collision>
        <geometry> <sphere radius="0.019" /> </geometry>
        <origin xyz="-0.0825 0.0 -0.04" rpy="0 0 0" />
      </collision>       
    </link>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <parent link="${prefix}base_footprint" />
      <child link="${prefix}base_link" />
      <origin xyz="0.0 0.0 0.059" rpy="0 0 0" />
    </joint>

    <link name="${prefix}left_wheel_link">
      <visual> 
        <geometry> <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" /> </geometry>
        <material name="Black" />
      </visual>
      <collision> 
        <geometry> <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" /> </geometry>
      </collision>
      <inertial> <origin xyz="0 0 0" /> <mass value="${wheel_mass}" /> <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" /> </inertial>
    </link>

    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}left_wheel_link" />
      <origin xyz="0.04025 0.062 -0.024" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="800" velocity="100" /> <dynamics damping="0.5" friction="0.01" />
    </joint>

    <link name="${prefix}right_wheel_link">
      <visual> 
        <geometry> <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" /> </geometry>
        <material name="Black"/>
      </visual>
      <collision> 
        <geometry> <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" /> </geometry>
      </collision>
      <inertial> <origin xyz="0 0 0" /> <mass value="${wheel_mass}" /> <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" /> </inertial>
    </link>

    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}right_wheel_link" />
      <origin xyz="0.04025 -0.062 -0.024" rpy="0 0 ${-M_PI}" />
      <axis xyz="0 -1 0" />
      <limit effort="800" velocity="100" /> <dynamics damping="0.5" friction="0.01" />
    </joint>

    <link name="${prefix}d435_link">
      <visual> <geometry> <box size="0.02 0.05 0.02"/> </geometry> <material name="Red"/> </visual>
    </link>
    <link name="${prefix}lidar_link" />

    <joint name="${prefix}d435_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}d435_link" />
      <origin xyz="0.10 0.0 0.075" rpy="0 0 0" /> 
    </joint>

    <joint name="${prefix}lidar_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}lidar_link" />
      <origin xyz="0.0 0.0 0.125" rpy="0 0 0" />
    </joint>

    <gazebo reference="${prefix}d435_link">
      <sensor name="fra2mo_camera" type="camera">
        <always_on>true</always_on>
        <update_rate>30.0</update_rate>
        <visualize>true</visualize>
        <topic>/fra2mo/camera/image</topic> 
        <camera name="fra2mo_head">
          <horizontal_fov>1.3962634</horizontal_fov>
          <image> <width>800</width> <height>800</height> <format>R8G8B8</format> </image>
          <clip> <near>0.02</near> <far>300</far> </clip>
        </camera>
      </sensor>
    </gazebo>

    <gazebo>
      <plugin name="ignition::gazebo::systems::DiffDrive" filename="libignition-gazebo-diff-drive-system.so">
        <left_joint>${prefix}left_wheel_joint</left_joint>
        <right_joint>${prefix}right_wheel_joint</right_joint>
        <wheel_separation>${wheel_axle}</wheel_separation>
        <wheel_radius>${wheel_radius}</wheel_radius>
        <odom_publish_frequency>50</odom_publish_frequency>
        <topic>/fra2mo/cmd_vel</topic>
      </plugin>
    </gazebo>

    </xacro:macro>
</robot>